services:
  - type: web
    name: basepulse-api
    env: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
